### ISSUE TITLE
Add to squid API: retrival of granteed agreement ids

### ISSUE THREAD

**Issue by jernejpregelj** [oceanprotocol/dev-ocean#149]
Squid API should have a way to retrieve granted agreement ids,

**Comment by Pedro-vk** [comment]
As a workaround, I did the following change on `squid-js`: https://github.com/oceanprotocol/squid-js/pull/243
It returns more data from past events. But probably is better to provide this information on the API in all the implementations.
We could add a method called `getGranted(did, address)` on `ocean.agreements`.
