### ISSUE TITLE
Document how to develop and where to host the documentation

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/dev-ocean#18]
It would be necessary to create a document that explains the structure that Ocean project is going to follow.
It should answer next questions:
- Are we going to use a tool that helps us to create the documentation as could be Sphinx?
- Are we going to deploy this documentation in a public documentation host?

**Comment by ttmc** [comment]
I assigned myself to this issue because I'm going to be helping a lot with documentation and these decisions will be made fairly soon. Stay tuned!
